---
name: Auto-merge TOC updates

on:
  pull_request:
    types: [opened]

jobs:
  enable-auto-merge-for-toc-update:
    name: Enable auto-merge for TOC file update
    if: github.event_name == 'pull_request' && github.actor == 'adamruzicka' && github.event.pull_request.title == 'Update TOC file from downstream'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Enable auto-merge for TOC file update
        run: gh pr merge ${{ github.event.pull_request.number }} --rebase --auto --delete-branch
        env:
          GH_TOKEN: ${{ github.token }}
