---
name: CI

on:
  pull_request:
  push:
    branches:
      - 'develop'
      - '*-stable'

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      steps:
        - name: Sleep for 120 seconds
          run: sleep 120
